Feature/file logging
peterservice-rnd/zman pull request #17
Opened 2019-02-11 12:14 UTC by AlexeyBorodin

2019-02-11 12:17 UTC, satoshi451 approved these changes
Approved

2019-02-11 12:23 UTC, satoshi451 approved these changes

2019-02-12 09:49 UTC, guras3 requested changes

2019-02-12 09:49 UTC, guras3 commented on zman-backend/src/test/kotlin/com/peterservice/zman/core/zookeeper/CuratorServiceTest.kt
> +     * that'user why can't use transactional API
косяк автозамены

2019-02-12 09:49 UTC, guras3 commented on zman-backend/src/main/kotlin/com/peterservice/zman/core/zookeeper/commands/CreateCommand.kt
> +        if (conflicts.isEmpty()) {
вот это ведь неправильно.
1) тут же ведь может создаться не 1 нода, а еще сколько угодно вложенных нод
2) наличие конфликта не означает, что ничего не создалось

2019-02-12 09:49 UTC, guras3 commented on zman-backend/src/main/kotlin/com/peterservice/zman/core/zookeeper/commands/DeleteCommand.kt
> +        actionBuilder
удаление ведь рекурсивное, по идее надо собрать все ноды, которые были удалены и создать N action ов

2019-02-12 09:49 UTC, guras3 commented on zman-backend/src/main/kotlin/com/peterservice/zman/core/zookeeper/commands/ReadCommand.kt
> +        actionBuilder
ну и тут ведь не только 1 нода зачитывается. может быть зачитано N нод если вызов с recursive = true
и как то странно логировать операции чтения

2019-02-13 09:25 UTC, guras3 approved these changes

2019-02-13 10:20 UTC, merged